language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - clang-3.4

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - ./prtty_tests ../test
