version: 2

jobs:
  working_directory: ~/prtty
  build:
    docker:
      - image: gcc@4.9.4
    steps:
      - checkout
      - run: mkdir build
      - run:
          name: Configure with CMake
          command: cmake ..
          working_directory: ~/prtty/build
      - run:
          name: Build
          command: cmake --build .
          working_directory: ~/prtty/build
      - run:
          name: Test example
          command: ./build/prtty_tests ./test
